name: Unit Tests

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - develop
      - master

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.18.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.x"

      - name: npm install and run test
        run: |
          npm i
          npm run test
